### ISSUE TITLE
Object function Array() { [native code] } has no method 'from'

### ISSUE THREAD

**Issue by mkvt141** [KevinVR/milights-bridge#12]
Followed the inctructions. Server is running but lights not doing anything.

After starting the server by sudo nodejs server.js I get the following error:

> Unhandled rejection TypeError: Object function Array() { [native code] } has no method 'from'
    at /home/pi/milights-bridge/node_modules/node-milight-promise/src/milight-v6-mixin.js:132:42
    at tryCatcher (/home/pi/milights-bridge/node_modules/node-milight-promise/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/milights-bridge/node_modules/node-milight-promise/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/milights-bridge/node_modules/node-milight-promise/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/milights-bridge/node_modules/node-milight-promise/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/pi/milights-bridge/node_modules/node-milight-promise/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/pi/milights-bridge/node_modules/node-milight-promise/node_modules/bluebird/js/release/promise.js:638:18)
    at null._onTimeout (/home/pi/milights-bridge/node_modules/node-milight-promise/node_modules/bluebird/js/release/timers.js:26:46)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by mwittig** [comment]
Which version of Node.js are you using?

```
sudo nodejs --version

**Comment by mkvt141** [comment]
Thank you!

**Old Node.js was the issue.** Installed using sudo apt-get install nodejs

I've installed new version of nodejs following this tutorial:
[https://www.instructables.com/id/Install-Nodejs-and-Npm-on-Raspberry-Pi/](url)

**Comment by mwittig** [comment]
Welcome. I think the issue can be closed now
