### ISSUE TITLE
Run on Windows 10? Error "git is not recognized as an internal or external command

### ISSUE THREAD

**Issue by KeithLaepple** [KevinVR/milights-bridge#5]
Hello, I'm trying to bring this up on Windows 10 but hitting the error below. I have Node-milight-promise working separately, so believe my NodeJS and NPM configurations are correct. 

FYI, in config.js, I do have "config.platform_islinux=false"

Have I missed a configuration step?

----------------------------------------------------------
c:\milights-bridge-master\node server.js
Setting up EJS...
Initialising Milight bridge connection (version v6)
Checking for updates...
'git' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:644
    throw err;
    ^

Error: Command failed: git rev-parse HEAD
'git' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at getLastCommitId (C:\Users\keith\Desktop\HABridge\milights-bridge-master\server.js:482:5)
    at refreshUpdateCache (C:\Users\keith\Desktop\HABridge\milights-bridge-master\server.js:503:14)
    at initIBox (C:\Users\keith\Desktop\HABridge\milights-bridge-master\server.js:312:2)
    at Server.<anonymous> (C:\Users\keith\Desktop\HABridge\milights-bridge-master\server.js:290:2)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by KeithLaepple** [comment]
Just noticed these errors resemble issue #1 , those I don't follow the solution in that thread.
